name: bloc_form_web
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc_form: ^0.32.0
  animations: ^2.0.11
  flutter_syntax_view: ^4.1.0
  flash: ^3.1.1
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.3+2
  auto_size_text: ^3.0.0
  liquid_progress_indicator_v2: ^0.5.0
  rxdart: ^0.27.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
  assets:
    - lib/examples/
