name: Form Bloc Web
on:
  push:
    branches:
      - master
    # paths:
    #   - 'bloc_form_web/**'
    #   - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./bloc_form_web

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'
        channel: 'stable'

    - name: Enable Flutter web
      run: flutter config --enable-web
      working-directory: ${{ env.working-directory }}

    - name: Install dependencies
      run: flutter packages get
      working-directory: ${{ env.working-directory }}

    - name: Build web
      run: flutter build web --web-renderer html
      working-directory: ${{ env.working-directory }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./bloc_form_web/build/web
